
 platform :ios, '9.0'

target '文艺星球' do
  
pod 'AFNetworking'
pod 'SDAutoLayout'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'DZNEmptyDataSet'
pod 'YYKit'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'AMapNavi'
pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit' 
pod 'Qiniu'
pod 'HappyDNS'

  use_frameworks!
  
end
